# Generated by Django 4.2.7 on 2023-11-26 13:44

import cadastro.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last_name')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='birthday')),
                ('phone', models.CharField(max_length=15, verbose_name='phone')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50, verbose_name='address')),
                ('cid', models.CharField(max_length=15, verbose_name='cid')),
                ('responsavel', models.BooleanField(default=False, verbose_name='responsavel')),
                ('nome_responsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='nome_responsavel')),
                ('alergia', models.CharField(blank=True, max_length=255, null=True, verbose_name='alergia')),
                ('sensibilidade', models.CharField(blank=True, max_length=255, null=True, verbose_name='sensibilidade')),
                ('profile_image', models.ImageField(upload_to=cadastro.models.user_directory_path, verbose_name='profile image')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_data', models.CharField(blank=True, max_length=255, null=True, verbose_name='qr code data')),
                ('qr_code_image', models.ImageField(upload_to=cadastro.models.user_directory_path, verbose_name='qr code image')),
                ('is_active', models.BooleanField(default=True)),
                ('gen_date', models.DateTimeField(auto_now_add=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='cadastro.member')),
            ],
        ),
        migrations.CreateModel(
            name='FileReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_report', models.FileField(blank=True, null=True, upload_to=cadastro.models.user_directory_path, verbose_name='document report')),
                ('upload_report_date', models.DateTimeField(blank=True, null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='cadastro.member')),
            ],
        ),
        migrations.CreateModel(
            name='FilePrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_prescription', models.FileField(blank=True, null=True, upload_to=cadastro.models.user_directory_path, verbose_name='document prescription')),
                ('upload_prescription_date', models.DateTimeField(blank=True, null=True)),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='cadastro.member')),
            ],
        ),
    ]
